"""add geo relatinship

Revision ID: 96c4d50cb4df
Revises: 8bf6eebfe636
Create Date: 2024-05-22 11:44:50.304936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c4d50cb4df'
down_revision: Union[str, None] = '8bf6eebfe636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('geo_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'channel', 'geo', ['geo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channel', type_='foreignkey')
    op.drop_column('channel', 'geo_id')
    # ### end Alembic commands ###
