"""add link for channel

Revision ID: b49026a05427
Revises: c9aa3832ae1a
Create Date: 2024-04-20 10:02:42.194392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b49026a05427'
down_revision: Union[str, None] = 'c9aa3832ae1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('link', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'link')
    # ### end Alembic commands ###
